"""
Generate Postfix configuration files from database.
Called when providers or access control settings change.
"""
import subprocess
import os
from pathlib import Path
from sqlalchemy.orm import Session
from backend.database import SessionLocal
from backend.models import Provider, AllowedClient, ProviderStatus
from backend.config import settings


POSTFIX_DIR = "/etc/postfix"


def generate_main_cf(db: Session, relay_port: int = 2525) -> str:
    """Generate main.cf content based on current providers and clients."""

    providers = db.query(Provider).filter(
        Provider.status != ProviderStatus.DISABLED
    ).all()

    clients = db.query(AllowedClient).filter(
        AllowedClient.is_active == True
    ).all()

    # Build mynetworks — ONLY localhost (internal pipe transport communication).
    # IP whitelist is handled by access_server.py via TCP lookup (real-time, no reload).
    mynetworks = ["127.0.0.0/8"]

    has_smtp_auth_clients = any(c.client_type == "smtp_auth" for c in clients)
    has_ip_clients = any(c.client_type == "ip" for c in clients)

    # Determine default relayhost
    default_provider = next((p for p in providers if p.is_default), None)
    if not default_provider and providers:
        default_provider = providers[0]

    # Postfix myhostname must be a valid FQDN, not an IP address
    import ipaddress
    try:
        ipaddress.ip_address(settings.hostname)
        postfix_hostname = "simplerelay.local"
    except ValueError:
        postfix_hostname = settings.hostname

    postfix_domain = postfix_hostname.split('.', 1)[1] if '.' in postfix_hostname else 'local'

    config = f"""# SimpleRelay — auto-generated, do not edit manually
# Generated by SimpleRelay config manager

compatibility_level = 3.6
smtpd_banner = {postfix_hostname} ESMTP
biff = no
append_dot_mydomain = no

# Network
inet_interfaces = all
inet_protocols = ipv4
smtp_address_preference = ipv4

# Hostname
myhostname = {postfix_hostname}
mydomain = {postfix_domain}
myorigin = $mydomain
mydestination =

# Relay restrictions — policy server checks IP+sender at RCPT TO time
mynetworks = {" ".join(mynetworks)}
smtpd_relay_restrictions = permit_mynetworks"""

    if has_smtp_auth_clients:
        config += """\n    permit_sasl_authenticated"""

    # Policy server checks IP+sender authorization in real-time from DB
    config += """\n    check_policy_service inet:127.0.0.1:9199"""

    config += """\n    reject"""

    # Stealth pipe transport — all outbound goes through Python → SOCKS5 → provider
    config += """

# Outbound transport: Python pipe (stealth SOCKS5 proxy, EHLO as [IP])
default_transport = simplerelay-pipe"""

    # Keep relayhost/sasl as fallback (used only if default_transport is disabled)
    if default_provider:
        config += f"""

# Fallback relay (not used with pipe transport)
#relayhost = [{default_provider.smtp_host}]:{default_provider.smtp_port}"""

    config += f"""

# Sender-dependent relay routing (fallback)
#sender_dependent_relayhost_maps = hash:{POSTFIX_DIR}/sender_relay"""

    # SASL authentication to upstream (fallback)
    config += f"""

# SASL auth to upstream (fallback, pipe transport handles auth directly)
#smtp_sasl_auth_enable = yes
#smtp_sasl_password_maps = hash:{POSTFIX_DIR}/sasl_passwd
#smtp_sasl_security_options = noanonymous
#smtp_sasl_mechanism_filter = plain, login
#smtp_sender_dependent_authentication = yes"""

    # TLS
    config += """

# TLS
smtp_tls_security_level = encrypt
smtp_tls_CAfile = /etc/ssl/certs/ca-certificates.crt
smtp_tls_session_cache_database = btree:${data_directory}/smtp_scache
smtp_tls_loglevel = 1"""

    # SASL server (for client auth)
    if has_smtp_auth_clients:
        config += f"""

# SASL server for client authentication
smtpd_sasl_auth_enable = yes
smtpd_sasl_type = cyrus
smtpd_sasl_path = smtpd
smtpd_sasl_security_options = noanonymous"""

    # Stealth mode — strip internal Received headers and relay Message-ID on outbound
    config += f"""

# Stealth mode: strip relay traces on outbound
smtp_header_checks = regexp:{POSTFIX_DIR}/smtp_header_checks
"""

    # Message limits
    config += """
# Limits
message_size_limit = 52428800
mailbox_size_limit = 0

# Pass environment variables to pipe transports (pipe_transport.py needs DB access)
import_environment = RELAY_DATABASE_URL RELAY_FERNET_KEY RELAY_PUBLIC_IP TZ
export_environment = RELAY_DATABASE_URL RELAY_FERNET_KEY RELAY_PUBLIC_IP TZ
"""

    return config


def generate_sasl_passwd(db: Session) -> str:
    """Generate sasl_passwd file with upstream credentials.
    Uses sender email as key (with smtp_sender_dependent_authentication)
    to support multiple accounts on the same SMTP server.
    """
    from backend.services.crypto import decrypt_password

    providers = db.query(Provider).filter(
        Provider.status.in_([ProviderStatus.ACTIVE, ProviderStatus.ERROR]),
        Provider.is_locked == False,
    ).all()

    seen = {}
    lines = []
    for p in providers:
        if p.username and p.password_encrypted:
            try:
                password = decrypt_password(p.password_encrypted)
            except Exception:
                password = p.password_encrypted
            lines.append(f"{p.email} {p.username}:{password}")
            relay_key = f"[{p.smtp_host}]:{p.smtp_port}"
            if relay_key not in seen:
                seen[relay_key] = True
                lines.append(f"{relay_key} {p.username}:{password}")

    return "\n".join(lines) + "\n" if lines else ""


def generate_smtp_header_checks() -> str:
    """Generate smtp_header_checks for stealth mode.
    Strips internal Received headers and relay-generated Message-ID
    so upstream provider sees clean email as if sent directly.
    """
    hostname_escaped = settings.hostname.replace(".", r"\.")
    return f"""# SimpleRelay stealth mode — auto-generated
# Strip ALL internal Received headers (upstream will add its own)
/^Received:.*by.*SimpleRelay/    IGNORE
/^Received:.*\\b(172\\.1[6-9]\\.|172\\.2[0-9]\\.|172\\.3[01]\\.|10\\.|192\\.168\\.|127\\.0\\.)/    IGNORE
/^Received:.*{hostname_escaped}/    IGNORE

# Strip Message-ID generated by relay (upstream will generate proper one)
/^Message-Id:.*@{hostname_escaped}/    IGNORE
"""


def generate_sender_relay(db: Session) -> str:
    """Generate sender_dependent_relayhost_maps."""
    providers = db.query(Provider).filter(
        Provider.status.in_([ProviderStatus.ACTIVE, ProviderStatus.ERROR]),
        Provider.is_locked == False,
    ).all()

    lines = []
    for p in providers:
        lines.append(f"{p.email} [{p.smtp_host}]:{p.smtp_port}")

    return "\n".join(lines) + "\n" if lines else ""


def write_and_reload(db: Session, relay_port: int = 2525):
    """Write all config files and reload Postfix."""

    # Write main.cf
    main_cf = generate_main_cf(db, relay_port)
    Path(f"{POSTFIX_DIR}/main.cf").write_text(main_cf)

    # Write sasl_passwd
    sasl = generate_sasl_passwd(db)
    sasl_path = Path(f"{POSTFIX_DIR}/sasl_passwd")
    sasl_path.write_text(sasl)
    os.chmod(sasl_path, 0o600)

    # Write sender_relay
    sender_relay = generate_sender_relay(db)
    sender_path = Path(f"{POSTFIX_DIR}/sender_relay")
    sender_path.write_text(sender_relay)

    # Write smtp_header_checks (stealth mode)
    header_checks = generate_smtp_header_checks()
    Path(f"{POSTFIX_DIR}/smtp_header_checks").write_text(header_checks)

    # Write SASL smtpd.conf for Cyrus
    sasl_conf_dir = Path(f"{POSTFIX_DIR}/sasl")
    sasl_conf_dir.mkdir(exist_ok=True)
    Path(f"{sasl_conf_dir}/smtpd.conf").write_text(
        "pwcheck_method: auxprop\n"
        "auxprop_plugin: sasldb\n"
        "mech_list: PLAIN LOGIN\n"
    )

    # Sync SMTP auth clients to sasldb2
    _sync_sasldb(db)

    # Rebuild hash maps
    try:
        subprocess.run(["postmap", f"{POSTFIX_DIR}/sasl_passwd"], check=True)
        subprocess.run(["postmap", f"{POSTFIX_DIR}/sender_relay"], check=True)
        subprocess.run(["postfix", "reload"], check=True)
    except subprocess.CalledProcessError as e:
        raise RuntimeError(f"Postfix reload failed: {e}")


def _sync_sasldb(db: Session):
    """Sync AllowedClient SMTP auth credentials to sasldb2."""
    hostname = settings.hostname

    clients = db.query(AllowedClient).filter(
        AllowedClient.client_type == "smtp_auth",
        AllowedClient.is_active == True,
    ).all()

    # Clear existing sasldb
    sasldb_path = "/etc/sasldb2"
    if os.path.exists(sasldb_path):
        os.remove(sasldb_path)

    for client in clients:
        if client.smtp_username and client.smtp_password_plain:
            try:
                subprocess.run(
                    ["saslpasswd2", "-p", "-c", "-u", hostname, client.smtp_username],
                    input=client.smtp_password_plain.encode(),
                    check=True,
                    capture_output=True,
                )
            except (subprocess.CalledProcessError, FileNotFoundError):
                pass

    # Fix permissions for Postfix
    if os.path.exists(sasldb_path):
        os.chmod(sasldb_path, 0o644)


def init_postfix():
    """Initialize Postfix with minimal config on first run."""
    db = SessionLocal()
    try:
        write_and_reload(db)
    finally:
        db.close()


if __name__ == "__main__":
    import sys
    if "--init" in sys.argv:
        init_postfix()